name: goreleaser

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
      -
        name: Check PR Merge and Check Status
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ] && [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "PR merged to main with all checks passed. Running GoReleaser..."
            # Run GoReleaser command here
          else
            echo "Skipping GoReleaser: Not a push to main branch or checks failed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
