# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Voioo < Formula
  desc "A simple todo list manager written in Go"
  homepage "https://github.com/voioo/td"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voioo/td/releases/download/v0.2.2/td_0.2.2_Darwin_x86_64.tar.gz"
      sha256 "d3b97e317c91fe84d820122f2354971ee5c8abcc79d3dbc6e4f79034bf35577b"

      def install
        bin.install "td"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voioo/td/releases/download/v0.2.2/td_0.2.2_Darwin_arm64.tar.gz"
      sha256 "0429911509cf330f828ed8208f1e4ddb6d4bcb9cb741e41ad5af3c539fcafd37"

      def install
        bin.install "td"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voioo/td/releases/download/v0.2.2/td_0.2.2_Linux_arm64.tar.gz"
      sha256 "d9594ffb1beccf8f4fd79fd7cae58b407563a7befc5b87a319c4797fc422f204"

      def install
        bin.install "td"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/voioo/td/releases/download/v0.2.2/td_0.2.2_Linux_x86_64.tar.gz"
      sha256 "a41c4618ea7b9da1c6250fbb2429907f4abc1464f14e12c0a3ce9a8a37ddc44f"

      def install
        bin.install "td"
      end
    end
  end

  test do
    system "#{bin}/td"
  end
end
