# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Voioo < Formula
  desc "A simple todo list manager written in Go"
  homepage "https://github.com/voioo/td"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/voioo/td/releases/download/v0.1.7/td_0.1.7_Darwin_x86_64.tar.gz"
      sha256 "93c99d25e2c751a0cc31fa0a3369dad8af1ea9b6a7815d634c867e24be20e56e"

      def install
        bin.install "td"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/voioo/td/releases/download/v0.1.7/td_0.1.7_Darwin_arm64.tar.gz"
      sha256 "fcc237396f279c8c6b4483d08156f390ca66712d83610b35a222ec71b07d69a6"

      def install
        bin.install "td"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/voioo/td/releases/download/v0.1.7/td_0.1.7_Linux_x86_64.tar.gz"
      sha256 "caf7bdc2baf8de8c825358418c3435c7a678298c8ba7b10802dd439d770fa706"

      def install
        bin.install "td"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voioo/td/releases/download/v0.1.7/td_0.1.7_Linux_arm64.tar.gz"
      sha256 "3ac15caec8d7683eb32fb4e2162039239487940d8f5805c41bf67ef3af56b1db"

      def install
        bin.install "td"
      end
    end
  end

  test do
    system "#{bin}/td"
  end
end
