jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - name: Set snapshot flags for PR events
        if: github.event_name == 'pull_request'
        run: echo "flags=--snapshot" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean ${{ env.flags }}
          workdir: ./cmd/td
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}