name: goreleaser

on:
  workflow_dispatch:
  pull_request:
  push:
    tags: ['v*']

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.1
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean ${{ env.flags }}
          workdir: ./cmd/td
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}